"""Platform-independent product semantics. Adapters must not reinterpret these types."""

from worktree_review.core.config import (
    ProviderConfiguration,
    UserConfiguration,
    load_user_configuration,
)
from worktree_review.core.errors import (
    BudgetExhaustedError,
    ContextGatherError,
    GitRequiredError,
    InvalidInvocationError,
    MergeConflictError,
    MergeConstructionError,
    PolicyValidationError,
    ProviderError,
    ReviewWorktreeError,
    UnimplementedStageError,
    WorktreeReviewError,
)
from worktree_review.core.findings import (
    ChangeKind,
    EvidenceBand,
    EvidenceSource,
    EvidenceSpan,
    Finding,
    Severity,
)
from worktree_review.core.gate import (
    GateEvaluationInput,
    evaluate_gate,
    finding_blocks_under_policy,
)
from worktree_review.core.identity import (
    MergeCandidateIdentity,
    PolicyVersionIdentity,
    ProposedSource,
    ResolvedCommitPair,
    ReviewIdentity,
    ReviewRequestKey,
)
from worktree_review.core.pipeline import ReviewRequest, run_review_pipeline
from worktree_review.core.policy import ComputePolicy, ReviewPolicy, load_builtin_review_policy
from worktree_review.core.report import (
    ComputePolicyDisclosure,
    CoverageRecord,
    ExecutionRecord,
    GateState,
    ReviewCallPlan,
    ReviewProgressEvent,
    ReviewReport,
    StageName,
    StageOutcome,
    StageStatus,
)

__all__ = [
    "BudgetExhaustedError",
    "ChangeKind",
    "ComputePolicy",
    "ComputePolicyDisclosure",
    "ContextGatherError",
    "CoverageRecord",
    "EvidenceBand",
    "EvidenceSource",
    "EvidenceSpan",
    "ExecutionRecord",
    "Finding",
    "GateEvaluationInput",
    "GateState",
    "GitRequiredError",
    "InvalidInvocationError",
    "MergeCandidateIdentity",
    "MergeConflictError",
    "MergeConstructionError",
    "PolicyValidationError",
    "PolicyVersionIdentity",
    "ProposedSource",
    "ProviderConfiguration",
    "ProviderError",
    "ResolvedCommitPair",
    "ReviewCallPlan",
    "ReviewIdentity",
    "ReviewPolicy",
    "ReviewProgressEvent",
    "ReviewReport",
    "ReviewRequest",
    "ReviewRequestKey",
    "ReviewWorktreeError",
    "Severity",
    "StageName",
    "StageOutcome",
    "StageStatus",
    "UnimplementedStageError",
    "UserConfiguration",
    "WorktreeReviewError",
    "evaluate_gate",
    "finding_blocks_under_policy",
    "load_builtin_review_policy",
    "load_user_configuration",
    "run_review_pipeline",
]
